### ISSUE TITLE
Ferdi flatpak fails to launch as it tries to install sqlite3

### ISSUE THREAD

**Issue by dcermak** [getferdi/ferdi#1072]
**Bug description:**

The flatpak of Ferdi fails to launch as off today (maybe already yesterday, but I haven't restarted it since Sunday).

**Steps to reproduce:**

```ShellSession
# flatpak run com.getferdi.Ferdi
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:2) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:2) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:2) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:2) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
Starting local server on port 45569
Knex: run
$ npm install sqlite3 --save
Error: ENOENT, node_modules/sqlite3/lib/binding/electron-v8.2-linux-x64/node_sqlite3.node not found in /app/Ferdi/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as .node] (electron/js2c/asar.js:146:27)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/Ferdi/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
info: serving app on http://Boreas:45569
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
```

Note that the `npm install sqlite3 --save` part is invoked by ferdi itself and not by me. I think that that's also the underlying issue here: for some reason Ferdi, or one of its dependencies now tries to fetch sqlite3 and save it to its flatpak installation folder. However, that is forbidden in flatpaks by design (iirc) and thus fails. My guess is that the Ferdi flatpak should include a bundled version of sqlite3 as well.

**Expected behavior**

Ferdi should launch

**Environment:**

- Operating System: openSUSE Tumbleweed
- Ferdi Version: 5.5.0 via flathub
- Server: Using without an account

- Debug information:
n/a

**Comment by aaronpkelly** [comment]
Similar behavior for me on NixOS with [Ferdi 5.5.0](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/applications/networking/instant-messengers/ferdi/default.nix#L12)

```
$ nix-shell -p ferdi
[nix-shell:~]$ ferdi
(ferdi:3130): Gtk-WARNING **: 07:13:16.336: Theme parsing error: colors.css:71:44: Invalid number for color value
(ferdi:3130): Gtk-WARNING **: 07:13:16.337: Theme parsing error: colors.css:72:44: Invalid number for color value
(ferdi:3130): Gtk-WARNING **: 07:13:16.337: Theme parsing error: colors.css:74:53: Invalid number for color value
(ferdi:3130): Gtk-WARNING **: 07:13:16.337: Theme parsing error: colors.css:75:53: Invalid number for color value
(ferdi:3130): Gtk-WARNING **: 07:13:16.337: Theme parsing error: colors.css:76:56: Invalid number for color value
(ferdi:3130): Gtk-WARNING **: 07:13:16.337: Theme parsing error: colors.css:77:65: Invalid number for color value
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:3130) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:3130) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:3130) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:3130) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
Starting local server on port 45569
Knex: run
$ npm install sqlite3 --save
Error: libstdc++.so.6: cannot open shared object file: No such file or directory
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/nix/store/vxp3ybwsamf3hsid3xcxdxw890qk41pa-ferdi-5.5.0/opt/Ferdi/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
info: serving app on http://127.0.0.1:45569

[nix-shell:~]$
```

**Comment by dcermak** [comment]
The issue disappeared for me for some reason after rebooting. No idea why, but maybe that'll solve the issue for you as well?

**Comment by pliski** [comment]
still broke in Nixos 20.09:
```sh
...
$ npm install sqlite3 --save
Error: libstdc++.so.6: cannot open shared object file: No such file or directory
      at process.func (electron/js2c/asar.js:140:31)
...
```

even after a reboot.

**Comment by mbbroberg** [comment]
Same happening via flatpak on Fedora 33. I've manually updated flatpak and `repair`ed Ferdi, but it hasn't fixed the issue of what seems like node missing some sqlite3 library (`node_modules/sqlite3/lib/binding/electron-v8.2-linux-x64/node_sqlite3.node`).

**Comment by vraravam** [comment]
Closing the issue since it seems to have been at the user's OS level.

@dcermak - please try with the latest nightlies found here: http://github.com/getferdi/nightlies/releases.
