### ISSUE TITLE
App threw an error during load - Failed to start Ferdi

### ISSUE THREAD

**Issue by huyhoang8398** [getferdi/ferdi#1207]
**Bug description:**
App threw an error during load - Failed to start Ferdi

**Steps to reproduce:**
1. Run ferdi

```bash
App threw an error during load
Error: ENOENT: no such file or directory, open '/usr/lib/ferdi/app.asar.unpacked/node_modules/mac-screen-capture-permissions/package.json'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:364:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.internalBinding.internalModuleReadJSON (electron/js2c/asar.js:674:19)
    at readPackage (internal/modules/cjs/loader.js:256:34)
    at readPackageExports (internal/modules/cjs/loader.js:308:15)
    at applyExports (internal/modules/cjs/loader.js:450:20)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:637:31)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/usr/lib/ferdi/app.asar.unpacked/node_modules/mac-screen-capture-permissions/package.json'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:364:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.internalBinding.internalModuleReadJSON (electron/js2c/asar.js:674:19)
    at readPackage (internal/modules/cjs/loader.js:256:34)
    at readPackageExports (internal/modules/cjs/loader.js:308:15)
    at applyExports (internal/modules/cjs/loader.js:450:20)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:637:31)
```
**Expected behavior**
Can start Ferdi

**Environment:**

- Operating System: Archlinux Kernel:  5.10.16-arch1-1
- Ferdi Version:  ferdi-git 5.6.0
- Server: Ferdi

**Comment by dpeukert** [comment]
ferdi-git maintainer here, I'm aware of the error, but haven't yet got around to looking into it more. In the meanwhile, if anyone needs to build the package, downloading [an older snapshot of the package](https://aur.archlinux.org/cgit/aur.git/snapshot/aur-4f8130bfff72f34453b92ace51d7e060073d59f8.tar.gz) and adding `#commit=846241d2da3134a68f011fb843be14a71c87f86a` to the end of line 19 should work.

**Comment by dpeukert** [comment]
ferdi-git should now be fixed, sorry for the delay. I've worked around the error by basically getting rid of the `mac-screen-capture-permissions` package, which obviously isn't a fix for the underlying issue, but it seems to be working on the Linux side with no issues: https://aur.archlinux.org/cgit/aur.git/plain/remove-mac-screen-capture-permissions.diff?h=ferdi-git

**Comment by huyhoang8398** [comment]
Thanks @dpeukert. It works perfect now. I will close this issue. Feel free to re open if needed
