### ISSUE TITLE
installing production dependencies  platform=linux arch=armv7l appDir=/home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/build   ⨯ npm exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

### ISSUE THREAD

**Issue by Marietto2008** [getferdi/ferdi#1562]
Hello to everyone.

I've tried to install ferdi on my jetson nano (where it runs ubuntu 21.04 for arm64 for tegra platform) using yunest (https://github.com/fsquillace/junest). So,first of all I have installed junest on my jetson nano like this :

$ git clone git://github.com/fsquillace/junest ~/.local/share/junest
$ export PATH=~/.local/share/junest/bin:$PATH
$ junest setup
$ pacman -Syy
$ git clone  https://aur.archlinux.org/ferdi.git 
$ cd ferdi
$ makepkg -si

all went good until here :

```
[1m[32m==>(B[m[1m Making package: ferdi 5.5.0-10 (Thu Jun 24 17:08:35 2021)(B[m
[1m[32m==>(B[m[1m Checking runtime dependencies...(B[m
[1m[32m==>(B[m[1m Checking buildtime dependencies...(B[m
[1m[32m==>(B[m[1m Retrieving sources...(B[m
[1m[34m  ->(B[m[1m Found ferdi-5.5.0-10.tar.gz(B[m
[1m[34m  ->(B[m[1m Found ferdi-5.5.0-10-recipes.tar.gz(B[m
[1m[34m  ->(B[m[1m Found ferdi-5.5.0-10-internal-server.tar.gz(B[m
[1m[34m  ->(B[m[1m Found fix-autostart-path.diff(B[m
[1m[32m==>(B[m[1m Validating source files with sha256sums...(B[m
[1m[32m==>(B[m[1m Extracting sources...(B[m
[1m[34m  ->(B[m[1m Extracting ferdi-5.5.0-10.tar.gz with bsdtar(B[m
[1m[34m  ->(B[m[1m Extracting ferdi-5.5.0-10-recipes.tar.gz with bsdtar(B[m
[1m[34m  ->(B[m[1m Extracting ferdi-5.5.0-10-internal-server.tar.gz with bsdtar(B[m
[1m[32m==>(B[m[1m Starting prepare()...(B[m
patching file src/stores/AppStore.js

> ferdi@5.5.0 postinstall /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0
> npx lerna run prepare


> @meetfranz/theme@1.0.14 prepare /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/packages/theme
> tsc


> @meetfranz/ui@1.0.0 prepare /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/packages/ui
> tsc


> @meetfranz/forms@1.1.0 prepare /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/packages/forms
> tsc

up to date in 69.591s

16 packages are looking for funding
  run `npm fund` for details


> node-sass@4.14.1 install /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-arm-83/binding.node

> node-sass@4.14.1 postinstall /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

Binary found at /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-arm-83/binding.node
Testing binary
Binary is fine

> node-sass@6.0.0 install /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/node-sass/vendor/linux-arm-83/binding.node

> node-sass@6.0.0 postinstall /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/node-sass
> node scripts/build.js

Binary found at /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/node-sass/vendor/linux-arm-83/binding.node
Testing binary
Binary is fine
node-sass@4.14.1 /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/gulp-sass/node_modules/node-sass
node-sass@6.0.0 /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/node_modules/node-sass
[1m[32m==>(B[m[1m Removing existing $pkgdir/ directory...(B[m
[1m[32m==>(B[m[1m Starting build()...(B[m
[17:10:09] Requiring external module @babel/register
[17:10:16] Using gulpfile /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/gulpfile.babel.js
[17:10:16] Starting 'build'...
[17:10:16] Starting 'clean'...
[17:10:16] Finished 'clean' after 232 ms
[17:10:16] Starting 'mvSrc'...
[17:10:16] Starting 'mvPackageJson'...
[17:10:16] Starting 'mvLernaPackages'...
[17:10:17] Finished 'mvPackageJson' after 694 ms
[17:10:18] Finished 'mvLernaPackages' after 1.9 s
[17:10:18] Finished 'mvSrc' after 2.1 s
[17:10:18] Starting 'html'...
[17:10:18] Starting 'scripts'...
[17:10:18] Starting 'styles'...
[17:10:18] Starting 'recipes'...
[17:10:18] Starting 'recipeInfo'...
[17:10:21] Finished 'recipeInfo' after 2.65 s
[17:10:21] Finished 'html' after 2.66 s
[17:10:22] Finished 'styles' after 4.17 s
[17:10:40] Finished 'recipes' after 22 s
[17:10:57] Finished 'scripts' after 39 s
[17:10:57] Finished 'build' after 42 s
  • electron-builder  version=22.4.1 os=4.9.140
  • loaded configuration  file=/home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/electron-builder.yml
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • installing production dependencies  platform=linux arch=armv7l appDir=/home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0/build
  ⨯ npm exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Error output:

Error output:
npm WARN deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
npm WARN deprecated babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated babel-plugin-react-intl@3.0.1: this package has been renamed to babel-plugin-formatjs
npm WARN deprecated eslint-loader@1.9.0: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated html-webpack-plugin@4.0.0-beta.5: please switch to a stable version
npm WARN deprecated @babel/polyfill@7.7.0: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated mdi@1.9.33: The mdi package was renamed to @mdi/font after v2.2.43. Please rename in your package.json for future updates.
npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated wreck@6.3.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @types/jss@10.0.0: This is a stub types definition. jss provides its own type definitions, so you do not need this installed.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated @types/theming@2.0.0: This is a stub types definition. theming provides its own type definitions, so you do not need this installed.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated intl-messageformat-parser@1.4.0: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated @sentry/apm@5.10.2: Please migrate to @sentry/tracing; see: https://www.npmjs.com/package/@sentry/apm
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > electron-chromedriver@3.0.0 install /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0-10-home/.npm/_cacache/tmp/git-clone-da195500/node_modules/electron-chromedriver
npm ERR! prepareGitDep > node ./download-chromedriver.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! prepareGitDep npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! prepareGitDep npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep sh: warning: setlocale: LC_ALL: cannot change locale (it_IT.UTF-8)
npm ERR! prepareGitDep /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0-10-home/.npm/_cacache/tmp/git-clone-da195500/node_modules/electron-chromedriver/download-chromedriver.js:19
npm ERR! prepareGitDep   if (err != null) throw err
npm ERR! prepareGitDep                    ^
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Error: Failed to find Electron v3.0.0 for linux-arm at https://github.com/electron/electron/releases/download/v3.0.0/chromedriver-v3.0.0-linux-arm.zip
npm ERR! prepareGitDep     at Request.<anonymous> (/home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0-10-home/.npm/_cacache/tmp/git-clone-da195500/node_modules/nugget/index.js:169:61)
npm ERR! prepareGitDep     at Request.emit (events.js:315:20)
npm ERR! prepareGitDep     at Request.onRequestResponse (/home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0-10-home/.npm/_cacache/tmp/git-clone-da195500/node_modules/request/request.js:1059:10)
npm ERR! prepareGitDep     at ClientRequest.emit (events.js:315:20)
npm ERR! prepareGitDep     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
npm ERR! prepareGitDep     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
npm ERR! prepareGitDep     at TLSSocket.socketOnData (_http_client.js:509:22)
npm ERR! prepareGitDep     at TLSSocket.emit (events.js:315:20)
npm ERR! prepareGitDep     at addChunk (internal/streams/readable.js:309:12)
npm ERR! prepareGitDep     at readableAddChunk (internal/streams/readable.js:284:9)
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! electron-chromedriver@3.0.0 install: `node ./download-chromedriver.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the electron-chromedriver@3.0.0 install script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0-10-home/.npm/_logs/2021-06-24T17_12_36_306Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zi/Desktop/AURp/ferdi/src/ferdi-5.5.0-10-home/.npm/_logs/2021-06-24T17_12_36_733Z-debug.log
  stackTrace=
```

**Comment by kris7t** [comment]
It seems you're trying to build Ferdi 5.5.0, which is extremely old now, and probably can't be built with recent nodejs and npm toolchains.

You should try building from git `develop` or `nightly`.

We're hoping to resolve our current release signing issues and create a new GA 5.6.0 release, after which the releases should became up to date and buildable, too.

**Comment by Marietto2008** [comment]
can u give me what's the correct command that I can try to give ?

**Comment by kris7t** [comment]
Arch aur will just build an old version.

You should clone the Git repository and follow the build instructions.

**Comment by Marietto2008** [comment]
https://github.com/getferdi/ferdi/issues/1563

**Comment by vraravam** [comment]
Closing this issue since its not relevant.
