### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by Swandog** [getferdi/ferdi#1775]
**Bug description:**

Ferdi does not come up as a gui for me. It appears to run, but there is no window. When starting it from the command line, the error I get is `Cannot find module `tslib'`. This happens even with the nightly AppImage.

This happens whether you start it from the command line or from clicking on the launcher, but the error is only visible from the command line.

The full error:
```
ken@ken-XPS-15-9500:~/Downloads$ ./Ferdi-5.6.1-nightly.23.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'tslib'
Require stack:
- /tmp/.mount_Ferdi-FsAUmr/resources/app.asar/node_modules/@meetfranz/theme/lib/index.js
- /tmp/.mount_Ferdi-FsAUmr/resources/app.asar/environment.js
- /tmp/.mount_Ferdi-FsAUmr/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_Ferdi-FsAUmr/resources/app.asar/node_modules/@meetfranz/theme/lib/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
```

I've tested nightly 21, and that works. Nightly 22 (marked as broken) fails but for a different reason.

**Steps to reproduce:**

1. Download the latest AppImage from nightlies
2. Run the AppImage from the command line

**Expected behavior**
App should come up with a main window

**Screenshots**
N/A

**Environment:**

- Operating System: Ubuntu 20.04.2 LTS
- Ferdi Version: Happened in 5.6.1-nightly.23
- Server: Using without an account

- Debug information:

I can't open Ferdi, and I don't have any Crash Reports

**Comment by vraravam** [comment]
@Swandog - I have fixed this issue earlier today. Please revert to the nightly (v21) - since both v22 and v23 were broken for different reasons. Or you can wait for the next nightly which will be released in approx 8 hours.
Closing the ticket now.

**Comment by vraravam** [comment]
I have put the warning in the GH downloads page

**Comment by Swandog** [comment]
Thanks!

**Comment by vraravam** [comment]
@Swandog - just released the latest nightly with this fix. Please download and try

**Comment by Swandog** [comment]
Works great, thanks!
