### ISSUE TITLE
crash at startup in RHEL 8

### ISSUE THREAD

**Issue by brendanf** [getferdi/ferdi#2078]
**Bug description:**
I'm using Red Hat Enterprise Linux 8.  I've tried to install from the RPM, the AppImage, and the tarball.  In each case, Ferdi fails to launch, and gives the error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.Jpaf1P: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/brfurnea/Downloads/ferdi-5.6.2/resources/app.asar/node_modules/cld/index.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
```

**Steps to reproduce:**

1. Try to run Ferdi from application menu or command prompt

**Expected behavior**

Ferdi starts up.

**Screenshots**

**Environment:**

- Operating System: RHEL 8
- Ferdi Version: 5.6.2 (But I get the same error with Franz, so this is apparently something from before the fork?)
- Server: I don't even get there.

- Debug information:

N/A, unless there's a command line option to Ferdi to get additional debugging output.

**Comment by vraravam** [comment]
Please try the latest nightly - there were some issues with `cld` which have now been resolved.

**Comment by brendanf** [comment]
@vraravam I just tried it, unfortunately it gives the same error (with slightly different line number of course.)

**Comment by mizzunet** [comment]
Almost same error here for `5.6.4-nightly.23` on Arch.
Xanmod kernel

**Comment by mizzunet** [comment]
According https://www.cyberciti.biz/faq/linux-add-nodev-nosuid-noexec-options-to-temporary-storage-partitions/, setting `/tmp` `exec` option may make system vulnerable.

 `/tmp` was mounting with `noexec` option from `/etc/fstab`

**Comment by brendanf** [comment]
Ah, my `/tmp` is also mounted `noexec`. That is probably the problem. This is my work computer and I do not have permission to change it.  Is there an environmental variable or config option I can set for Ferdi to tell it to use a different temp directory?

**Comment by brendanf** [comment]
I just looked at this a little more, and executing Ferdi with `TMPDIR=/path/to/my/alternate/tmp ferdi` works!

**Comment by vraravam** [comment]
Looks like this is an issue due to the way @brendanf has their laptop setup? If so, we should close this ticket.

**Comment by brendanf** [comment]
@vraravam Mounting `/tmp` as `noexec` is apparently something that is suggested by some security experts, including the IT team at my university. When I was Googling to try to find a solution, I found out that this has come up with other applications using Electron, and [they say this should be fixed on the app side](https://github.com/electron/electron/issues/24242#issuecomment-648914819).
