### ISSUE TITLE
Latest snap upgrade has broke all my chats configuration

### ISSUE THREAD

**Issue by redno2** [getferdi/ferdi#2187]
Latest snap upgrade has broke all my chats configuration, there is no anymore config, this just started as a fresh installation.

```
$ snap info ferdi
name:      ferdi
summary:   All your messaging services in one place
publisher: Ferdi (getferdi)
store-url: https://snapcraft.io/ferdi
contact:   hello@getferdi.com
license:   unset
description: |
  Ferdi is a messaging browser that allows you to combine your favorite messaging services into one
  application.
commands:
  - ferdi
snap-id:      c9FsJPOVsNaH3lLn0KtmU76g0CKm1N6R
tracking:     latest/stable
refresh-date: aujourd'hui à 20h38, heure des Rocheuses
channels:
  latest/stable:    5.6.3            2021-11-07 (113) 122MB -
  latest/candidate: ↑                                       
  latest/beta:      5.6.3-beta.4     2021-11-07 (111) 122MB -
  latest/edge:      5.6.3-nightly.54 2021-11-07 (110) 122MB -
installed:          5.6.3                       (113) 122MB -
```

![image](https://user-images.githubusercontent.com/3406132/140661169-9e85a99c-f56e-4a3d-b23f-826405289f58.png)

**Environment:**

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

- Server: Ferdi, Franz, Using without an account 

- Debug information:
```
{"host":{"platform":"linux","release":"5.13.0-20-generic","screens":[{"id":3,"bounds":{"x":0,"y":0,"width":3440,"height":1440},"workArea":{"x":0,"y":0,"width":3440,"height":1440},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":3440,"height":1440},"displayFrequency":59,"workAreaSize":{"width":3440,"height":1440},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":7,"bounds":{"x":3440,"y":0,"width":2560,"height":1440},"workArea":{"x":3440,"y":0,"width":2560,"height":1440},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"displayFrequency":59,"workAreaSize":{"width":2560,"height":1440},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{}],"devRecipes":[],"services":[],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[bound ]'",{}]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/snap/ferdi/113/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/snap/ferdi/113/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdi/113/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/snap/ferdi/113/resources/app.asar/routes.js:1:2781)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/snap/ferdi/113/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/snap/ferdi/113/resources/app.asar/I18n.js:1:842)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/snap/ferdi/113/resources/app.asar/components/layout/Sidebar.js:1:2094)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (/snap/ferdi/113/resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/snap/ferdi/113/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/snap/ferdi/113/resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/snap/ferdi/113/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/snap/ferdi/113/resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/snap/ferdi/113/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/snap/ferdi/113/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdi/113/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/snap/ferdi/113/resources/app.asar/routes.js:1:2781)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/snap/ferdi/113/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/snap/ferdi/113/resources/app.asar/I18n.js:1:842)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (/snap/ferdi/113/resources/app.asar/features/nightlyBuilds/Component.js:1:2135)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Jss (/snap/ferdi/113/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (/snap/ferdi/113/resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/snap/ferdi/113/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/snap/ferdi/113/resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/snap/ferdi/113/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/snap/ferdi/113/resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/snap/ferdi/113/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/snap/ferdi/113/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdi/113/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/snap/ferdi/113/resources/app.asar/routes.js:1:2781)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/snap/ferdi/113/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/snap/ferdi/113/resources/app.asar/I18n.js:1:842)\n    at Injector (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/snap/ferdi/113/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[bound _build]"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"default"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getUserWorkspaces"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":1646,"height":1207,"x":831,"y":127,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":3440,"height":1440}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":"300","wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false},"features":{}}}
```

Thanks

**Comment by redno2** [comment]
mhh after the rollback, I've made a snapshot and refresh the snap, so now it's on the new version 5.6.3, and everything is ok. Don't know what happened.. 

```
$ sudo snap save ferdi
Ensemble  Snap   Âge    Version  Version  Taille  Notes
6         ferdi  21.1s  5.6.2    48        238MB  -

$ sudo snap refresh ferdi
ferdi 5.6.3 par Ferdi (getferdi) mis à jour


```

**Comment by vraravam** [comment]
@redno2 - from my basic understanding of snaps, an upgrade would create a brand new profile for that new version of any app. If this is so, then the behavior is correct. @mhatvan - please comment

**Comment by mhatvan** [comment]
I assume snap copies over all data from old to new version,but needs to reinitialize everything and something went wrong. We still need to improve our snap support, but are blocked by electron-builder unfortunately.

**Comment by mbnoimi** [comment]
> mhh after the rollback, I've made a snapshot and refresh the snap, so now it's on the new version 5.6.3, and everything is ok. Don't know what happened..
> 
> ```
> $ sudo snap save ferdi
> Ensemble  Snap   Âge    Version  Version  Taille  Notes
> 6         ferdi  21.1s  5.6.2    48        238MB  -
> 
> $ sudo snap refresh ferdi
> ferdi 5.6.3 par Ferdi (getferdi) mis à jour
> ```

I've the same issue here but I couldn't restore my configurations! I'm really frustrated it seems snap package is unstable at all (https://github.com/getferdi/ferdi/issues/2270)

**Comment by mbnoimi** [comment]
I browsed `snap` config folder and I can see so many folders avaliable:
```
$ ls -lh
total 20K
drwxr-xr-x 5 laptop laptop 4.0K Nov 24 10:26 113
drwxr-xr-x 5 laptop laptop 4.0K Nov 22 17:08 126
drwxr-xr-x 5 laptop laptop 4.0K Nov 24 10:20 129
drwxr-xr-x 3 laptop laptop 4.0K Nov 19 21:56 common
lrwxrwxrwx 1 laptop laptop    3 Nov 24 10:26 current -> 113
$
```

**Comment by redno2** [comment]
appear again with the latest release 5.6.8 with snap.

```
cp -r 176/.config/Ferdi/* 179/.config/Ferdi/
```
fix the issue, some migration tools for snap version doesn't work
