### ISSUE TITLE
Shortcut "Disable service" only works when contextual menu is open

### ISSUE THREAD

**Issue by MrChocolatine** [getferdi/ferdi#2202]
**Bug description:**

The latest release 5.3.3 brought a keyboard shortcut to disable the current service. However, this shortcut only works when we open the contextual menu (right click) of a service.

_This is a follow-up to the feature request #2171_

**Steps to reproduce:**

Consider this scenario:

1. In the left sidebar I have 2 services, A and B
1. I am currently using service A
1. If I use the new shortcut to disable the service, nothing happens ❌
1. In the left sidebar, I click right click the icon of service A and I use the shortcut to disable the service, the service A is disabled (expected behaviour ✅)
1. In the left sidebar, I click right click the icon of service B and I use the shortcut to disable the service, the service B is disabled (expected behaviour ✅)

**Expected behavior**

The step (3) should work.
We should not need to open the contextual menu to trigger a keyboard shortcut.

**Environment:**

- Operating System: macOS
- Ferdi Version: 5.6.3
- Server: Without a server, without an account

- Debug information:

   For your information, before copying the debug info:
   - I closed and reopen Ferdi
   - I used the keyboard shortcut "Disable service" (not working)

<details>
<summary>Click to see debug information</summary>

```json
{
  "host": {
    "platform": "darwin",
    "release": "19.6.0",
    "screens": [
      {
        "id": 69733824,
        "bounds": {
          "x": 0,
          "y": 0,
          "width": 1440,
          "height": 900
        },
        "workArea": {
          "x": 0,
          "y": 0,
          "width": 1440,
          "height": 900
        },
        "accelerometerSupport": "unknown",
        "monochrome": false,
        "colorDepth": 30,
        "colorSpace": "{primaries:BT709, transfer:IEC61966_2_1_HDR, matrix:RGB, range:FULL}",
        "depthPerComponent": 10,
        "size": {
          "width": 1440,
          "height": 900
        },
        "displayFrequency": 60,
        "workAreaSize": {
          "width": 1440,
          "height": 900
        },
        "scaleFactor": 2,
        "rotation": 0,
        "internal": true,
        "touchSupport": "unknown"
      },
      {
        "id": 4128835,
        "bounds": {
          "x": -247,
          "y": -1080,
          "width": 1920,
          "height": 1080
        },
        "workArea": {
          "x": -247,
          "y": -1080,
          "width": 1920,
          "height": 1080
        },
        "accelerometerSupport": "unknown",
        "monochrome": false,
        "colorDepth": 24,
        "colorSpace": "{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}",
        "depthPerComponent": 8,
        "size": {
          "width": 1920,
          "height": 1080
        },
        "displayFrequency": 60,
        "workAreaSize": {
          "width": 1920,
          "height": 1080
        },
        "scaleFactor": 1,
        "rotation": 0,
        "internal": false,
        "touchSupport": "unknown"
      }
    ]
  },
  "ferdi": {
    "version": "5.6.3",
    "electron": "15.3.0",
    "installedRecipes": [
      {
        "id": "discord",
        "version": "1.4.5"
      },
      {
        "id": "franz-custom-website",
        "version": "1.1.0"
      },
      {
        "id": "github",
        "version": "2.2.0"
      },
      {
        "id": "msteams",
        "version": "3.1.6"
      },
      {
        "id": "office365-owa",
        "version": "1.5.0"
      },
      {
        "id": "proton-mail",
        "version": "1.3.1"
      },
      {
        "id": "slack",
        "version": "1.3.3"
      },
      {
        "id": "twitter",
        "version": "1.2.0"
      },
      {}
    ],
    "devRecipes": [],
    "services": [
      {
        "id": "19450bd3-8459-4f74-979f-2410e2901b09",
        "recipe": "discord",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": true
      },
      {
        "id": "22eb3de3-7b89-4988-b81f-4d2a14279498",
        "recipe": "slack",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "78540d6f-dc94-4d6a-8437-5a5a059f0aaa",
        "recipe": "office365-owa",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "5cd2db96-96fb-40cb-9a4a-1fba8635e9db",
        "recipe": "msteams",
        "isAttached": false,
        "isActive": false,
        "isEnabled": false,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "9a9142b4-4c2d-4b02-9ebb-cf39508a8ac3",
        "recipe": "franz-custom-website",
        "isAttached": false,
        "isActive": false,
        "isEnabled": false,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "e95360e7-8618-4b4a-b586-9366ea196db0",
        "recipe": "proton-mail",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "5d2e47e3-2ae5-4510-a599-8f2b9b5f9114",
        "recipe": "proton-mail",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": true
      },
      {
        "id": "863e3512-b5e6-43c7-88ef-d8a310a5bb53",
        "recipe": "proton-mail",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": true
      },
      {
        "id": "1cce2f38-fb58-4e18-adc8-0762ae75c7c9",
        "recipe": "office365-owa",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": true
      },
      {
        "id": "3d078a0a-254f-45d5-9e07-779f44c17d7b",
        "recipe": "slack",
        "isAttached": false,
        "isActive": false,
        "isEnabled": false,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "9b63b6ce-a3a7-4750-a7e3-e451086c0770",
        "recipe": "proton-mail",
        "isAttached": false,
        "isActive": false,
        "isEnabled": false,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "20499afd-0487-4a15-9274-2f51f9d2a1c2",
        "recipe": "proton-mail",
        "isAttached": true,
        "isActive": true,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "8a030800-72a4-4bf9-abb5-9478246e0bb0",
        "recipe": "proton-mail",
        "isAttached": false,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": true,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      }
    ],
    "messages": [
      {
        "type": "error",
        "info": [
          "error",
          "Warning: Failed %s type: %s%s",
          "prop",
          "Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.",
          "\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2781)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:842)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:1328:7)"
        ]
      },
      {
        "type": "error",
        "info": [
          "error",
          "Warning: Failed %s type: %s%s",
          "prop",
          "Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.",
          "\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/Sidebar.js:1:2094)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2781)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:842)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:1328:7)"
        ]
      },
      {
        "type": "error",
        "info": [
          "error",
          "Warning: Failed %s type: %s%s",
          "prop",
          "Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.",
          "\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/features/nightlyBuilds/Component.js:1:2135)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2781)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:842)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:1328:7)"
        ]
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "getInfo"
        },
        "error": {},
        "response": {},
        "server": "You are using Ferdi without a server"
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "features"
        },
        "error": {},
        "response": {},
        "server": "You are using Ferdi without a server"
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "all"
        },
        "error": {},
        "response": {},
        "server": "You are using Ferdi without a server"
      },
      {
        "type": "error",
        "info": [
          "error",
          "Warning: Failed %s type: %s%s",
          "prop",
          "Invalid prop `actions.app` of type `Object` supplied to `_class2`, expected instance of `_class`.",
          "\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/features/webControls/containers/WebControlsScreen.js:1:1970)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at div\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/services/content/ServiceView.js:1:1504)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at div\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/services/content/Services.js:1:2080)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class2-with-actions))\n    at div\n    at div\n    at div\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2781)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:842)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:1328:7)"
        ]
      }
    ],
    "workspaces": [],
    "windowSettings": {
      "width": 1810,
      "height": 1080,
      "x": -137,
      "y": -1080,
      "displayBounds": {
        "x": -247,
        "y": -1080,
        "width": 1920,
        "height": 1080
      },
      "isMaximized": true,
      "isFullScreen": false
    },
    "settings": {
      "autoLaunchOnStart": false,
      "autoLaunchInBackground": false,
      "runInBackground": false,
      "reloadAfterResume": true,
      "enableSystemTray": true,
      "startMinimized": false,
      "confirmOnQuit": true,
      "minimizeToSystemTray": false,
      "closeToSystemTray": false,
      "privateNotifications": false,
      "clipboardNotifications": true,
      "notifyTaskBarOnMessage": false,
      "showDisabledServices": true,
      "showServiceName": false,
      "showMessageBadgeWhenMuted": true,
      "showDragArea": false,
      "enableSpellchecking": true,
      "spellcheckerLanguage": "en-us",
      "darkMode": false,
      "splitMode": false,
      "fallbackLocale": "en-US",
      "beta": false,
      "isAppMuted": false,
      "enableGPUAcceleration": true,
      "enableGlobalHideShortcut": false,
      "server": "You are using Ferdi without a server",
      "predefinedTodoServer": "https://app.franztodos.com",
      "autohideMenuBar": false,
      "lockingFeatureEnabled": false,
      "locked": false,
      "lockedPassword": "******",
      "useTouchIdToUnlock": true,
      "scheduledDNDEnabled": false,
      "scheduledDNDStart": "17:00",
      "scheduledDNDEnd": "09:00",
      "hibernateOnStartup": true,
      "hibernationStrategy": 1800,
      "wakeUpStrategy": 300,
      "inactivityLock": 0,
      "automaticUpdates": false,
      "universalDarkMode": false,
      "userAgentPref": "",
      "adaptableDarkMode": true,
      "accentColor": "#7266F0",
      "serviceRibbonWidth": 35,
      "iconSize": 20,
      "sentry": false,
      "nightly": false,
      "navigationBarBehaviour": "always",
      "searchEngine": "duckDuckGo",
      "useVerticalStyle": false,
      "alwaysShowWorkspaces": false,
      "liftSingleInstanceLock": false,
      "enableLongPressServiceHint": false,
      "proxyFeatureEnabled": false,
      "onlyShowFavoritesInUnreadCount": false,
      "locale": "en-US",
      "showServiceNavigationBar": false,
      "todoServer": "isUsingCustomTodoService",
      "customTodoServer": ""
    },
    "features": {},
    "user": "82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"
  }
}
```

</details>

**Comment by vraravam** [comment]
This is, unfortunately, how the context menu works. For eg, lets say there are 4 (any number > 1) services, the context menu for each (along with the shortcut accelerators) are contextual to that service. What you are asking for is a mechanism where the context menu accelerators are registered globally, but in which case, for them to not conflict with each other, the shortcut needs to be unique - which defeats the purpose of the "context menu". I'm not sure this is proper UX.

**Comment by MrChocolatine** [comment]
What? I am clearly not asking to change how the context menu works.

There is already the shortcut "Reload service", which is available as an option in the contextual menu (when clicking the icon of a service) and without having the contextual menu open.

We can reload a service on-demand, by using the keyboard shortcut.
Why is it not possible to do the same with the shortcut "Disable service"?

**Comment by vraravam** [comment]
ok - my mistake. I misunderstood that the intention was for the contextual menu should be available via shortcuts all the time. What you are asking is for the Disable service to work similar to the `View > Reload Service` menu?

**Comment by MrChocolatine** [comment]
Exactly @vraravam , to be able to disable a service on-demand using the keyboard shortcut, without the need to open the contextual menu 👍  .

**Comment by MrChocolatine** [comment]
I just updated the title of the issue, to be the most explicit possible, but the issue also applies to the (same) shortcut "Enable a service". I know these features are the same keyboard shortcut but just in case.
