### ISSUE TITLE
Notion Bug with google account

### ISSUE THREAD

**Issue by Insidevk18** [getferdi/ferdi#2206]
**Bug description:**

When opening the pop-up window to enter the Google account, Ferdi in the main window shows the following message: "Oh no! Notion has caused an error. Reload Notion. Try to automatically restore Notion in seconds ...". And so the loop repeats. The main window is booted and the pop-up window is still available to put the account, but it is in vain because it still cannot open the Notion.

Something additional:

 -In my Google account (for organizations) when I open the pop-up window to write my google account, when I enter the email and then the password, the pop-up window remains blank.

-In my Google account (normal account) when I write my email in the pop-up window I get the following message: "It is possible that the application or the browser is not secure. Try another browser. If you are already using a supported browser, you can try logging in again. "

**Steps to reproduce:**

1. Go to '.Notion (service)..'
2. Click on '..Try Notion Free..'
3. Scroll down to '.Continue with Google...'

**Expected behavior**

What consequently happens is that Ferdi only manages to open the pop-up window to place the google mail, but in the main window he shows the message: "Oh no! Notion has caused an error".

**Screenshots**

![image](https://user-images.githubusercontent.com/94028610/141044358-33c42e09-2ca1-4d3a-9c5c-ef51339e3b27.png)

![image](https://user-images.githubusercontent.com/94028610/141044257-1036e9bf-ead3-40a4-9765-cf4e0e3ee688.png)

![image](https://user-images.githubusercontent.com/94028610/141044317-1da09891-a9c5-4b06-8ef1-787df157d4b5.png)

![image](https://user-images.githubusercontent.com/94028610/141044413-58f0ad52-4c59-4188-b615-6d7778902784.png)

**Environment:**

- Operating System: Windows 10 
- Ferdi Version: 5.6.3  
- Server: Using without account 

- Debug information:

{"host":{"platform":"win32","release":"10.0.19042","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1360,"height":768},"workArea":{"x":0,"y":0,"width":1360,"height":738},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1360,"height":768},"displayFrequency":60,"workAreaSize":{"width":1360,"height":738},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{"id":"notion","version":"1.1.2"},{}],"devRecipes":[],"services":[{"id":"da355c46-7330-4940-a98f-aaed3086d35e","recipe":"notion","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"6e8b2032-39be-45bd-83e7-b01183bb079f","recipe":"notion","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\Sidebar.js:1:2094)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\features\\nightlyBuilds\\Component.js:1:2135)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Jss (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Insidevk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":0,"y":0,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1360,"height":768}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":"300","wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US"},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by sad270** [comment]
It seems to be UserAgent (UA) related bug can you try this https://github.com/getferdi/ferdi/issues/1350#issuecomment-927837413 ?

**Comment by Insidevk18** [comment]
> It seems to be UserAgent (UA) related bug can you try this [#1350 (comment)](https://github.com/getferdi/ferdi/issues/1350#issuecomment-927837413) ?

I'm sorry to bring bad news friend but I realized your method and it did not solve the problem with the notion service.  :(
Ferdi Version: 5.6.4-nightly.12

![imagen](https://user-images.githubusercontent.com/94028610/142958568-91919675-9190-4a6c-b5a6-dacc50fa290e.png)

![imagen](https://user-images.githubusercontent.com/94028610/142958592-6d48563f-4b5a-4c71-9045-5d15905591de.png)

![imagen](https://user-images.githubusercontent.com/94028610/142958607-9d05517a-d788-47b2-a8ad-3a4df4d2397d.png)

![imagen](https://user-images.githubusercontent.com/94028610/142958638-36dbb042-8239-4068-ae46-c9a3bb185768.png)

**Comment by marcmiro** [comment]
Hello, 
same issue on my side. In my case, I'm using MAC with Ferdi version 5.6.3. I did the procedure with the UA and issue persists.
Regards.

**Comment by axhamre** [comment]
Same issue here.

Ferdi: 5.6.6
MacOS: 11.6
