### ISSUE TITLE
[Bug]: Single process hanging and using a lot of CPU

### ISSUE THREAD

**Issue by alecive** [getferdi/ferdi#2252]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known working version of Ferdi

No idea

### Git SHA and/or build date

No idea

### Steps to reproduce

1. Go to Task Manager
2. Look at the Ferdi processes
3. There's usually one of the processes that has multiple threads (which I suspect is the one with the main app), and then a couple other single-thread processes that I'm not sure what they do
4. Sometimes, one of them decides to use all of my CPU (I'm on a Dell XPS 9510 so processing power is absolutely not a problem)
5. When that happens, I just kill it and go about my day; Ferdi works even with that process killed

### Expected Behavior

I wold like not to have that process and not to do the steps above.

### Actual Behavior

N/A

### Debug information

{"host":{"platform":"win32","release":"10.0.22000","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1728,"height":1080},"workArea":{"x":0,"y":0,"width":1728,"height":1032},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1728,"height":1080},"displayFrequency":60,"workAreaSize":{"width":1728,"height":1032},"scaleFactor":2,"rotation":0,"internal":true,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":0,"y":-1440,"width":3440,"height":1440},"workArea":{"x":0,"y":-1440,"width":3440,"height":1392},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":3440,"height":1440},"displayFrequency":60,"workAreaSize":{"width":3440,"height":1392},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{"id":"android-messages","version":"2.2.4"},{"id":"franz-custom-website","version":"1.0.3"},{"id":"gmail","version":"1.4.2"},{"id":"googlecalendar","version":"2.2.0"},{"id":"slack","version":"1.3.3"},{"id":"telegram","version":"3.2.4"},{"id":"whatsapp","version":"3.3.6"},{}],"devRecipes":[],"services":[{"id":"7104d98f-bfcd-45f6-9e98-3563aa344a11","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b759222f-4b08-4a70-80e7-a3e88f6374a7","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"9ee5efc3-2532-47c0-a054-f621d3496019","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"123840e1-7b48-40f0-bcc2-c3ca1e91b9b8","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"3f54cb85-586a-426a-8e30-7ff6c330fcf8","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"bfb13997-184e-4336-a66c-0d79f290e075","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"f20f2b3c-e997-4cb8-9db0-0a773d285c21","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"08745de1-e18a-4022-90e5-131a4ced9309","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"3126d68a-5c82-4aba-a534-95beb2956cc7","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\Sidebar.js:1:2094)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\features\\nightlyBuilds\\Component.js:1:2135)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Jss (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\aleci\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":960,"height":1032,"x":223,"y":20,"displayBounds":{"x":0,"y":0,"width":1728,"height":1080},"isMaximized":true,"isFullScreen":false},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":true,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":"10","sentry":false,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US","serviceLimit":5,"hibernate":false,"showServiceNavigationBar":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by alecive** [comment]
Update: these processes remain even after I close ferdi

![image](https://user-images.githubusercontent.com/4378663/142885208-98c359cf-15e7-4cc8-9dd7-77dbebfa6ad6.png)
