### ISSUE TITLE
[Bug]: Instagram goes to feed page rather than DMs page in 5.6.3

### ISSUE THREAD

**Issue by jeremymeyers** [getferdi/ferdi#2260]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

10.0.19043

### What arch are you using?

x64

### Last Known working version of Ferdi

5.6.1

### Steps to reproduce

Click on previously set up Instagram DMs service

### Expected Behavior

Instagram DMs page shows

### Actual Behavior

Instagram main feed page shows.  Clicking on "Mail" icon switches it over, but will reset upon restarting Ferdi

### Debug information

{"host":{"platform":"win32","release":"10.0.19043","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1920,"height":1200},"workArea":{"x":0,"y":0,"width":1920,"height":1200},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6600, 0.3320],  [0.3020, 0.6130],  [0.1500, 0.0630]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1200},"displayFrequency":59,"workAreaSize":{"width":1920,"height":1200},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{"id":"discord","version":"1.4.5"},{"id":"franz-custom-website","version":"1.1.0"},{"id":"github","version":"2.3.1"},{"id":"googlecalendar","version":"2.2.0"},{"id":"instagram","version":"2.2.4"},{"id":"messenger","version":"1.3.3"},{"id":"pushbullet","version":"1.0.2"},{"id":"telegram","version":"3.2.4"},{"id":"todoist","version":"1.3.1"},{"id":"tweetdeck","version":"1.2.2"},{"id":"twitter","version":"1.2.1"},{}],"devRecipes":[],"services":[{"id":"8799fc98-8fef-4d8f-87de-bdd9d2b624f1","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"c4fc6b9e-f858-466f-b0c8-602acdb74b51","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"d4b54314-5fa2-486e-87d4-e9d1fedacc3b","recipe":"instagram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"7a8232fe-68ba-42b3-9c11-bad7d6e6a5e0","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"04196eea-0d49-4c44-840e-16c7cb8ec25a","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"a0e0c050-0f4b-4281-add4-0aaadc7d7a49","recipe":"twitter","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c366a295-f10c-46dd-8a0b-0bc24344eb4c","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"baa12613-253d-4cd1-8cf9-5c316f1f7d41","recipe":"tweetdeck","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"bf125ed5-7465-47fe-bc3d-2b21f5b093b6","recipe":"github","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"e1f95aa3-6dc5-45e3-83e2-16293d444fd1","recipe":"todoist","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\Sidebar.js:1:2094)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\features\\nightlyBuilds\\Component.js:1:2135)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Jss (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":
s":{"width":1678,"height":1042,"x":199,"y":43,"displayBounds":{"x":0,"y":0,"width":1920,"height":1200},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":false,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"\"\\\"[\\\\\\\"en-US\\\\\\\"]\\\"\"","darkMode":false,"splitMode":false,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"https://api.getferdi.com","predefinedTodoServer":"https://todoist.com/app","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US","serviceLimit":5,"hibernate":false,"showServiceNavigationBar":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"needToWaitToProceed":false,"isSpellcheckerPremiumFeature":false,"isSpellcheckerIncludedInCurrentPlan":true,"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isWorkspaceEnabled":true,"isAnnouncementsEnabled":true,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCommunityRecipesIncludedInCurrentPlan":true,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by vraravam** [comment]
The service URL is hardcoded. What you are asking is for Ferdi to remember where you left off - even upon restarting Ferdi. This can be an enhancement that someone can contribute code towards. But, unfortunately, wont be something that we can directly implement.

**Comment by LukoFoks** [comment]
**Duplicate** of #2201
