### ISSUE TITLE
[Bug]: RPM Package Dependency Issue

### ISSUE THREAD

**Issue by jshand2015** [getferdi/ferdi#2314]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Other Linux

### Server

Ferdi

### Operating System Version

opensuse tumbleweed

### What arch are you using?

x64

### Last Known working version of Ferdi

5.6.3

### Git SHA and/or build date

7ab8abe / FerdiBot released this 08 Nov 2021

### Steps to reproduce

1.  click on the rpm file to start install.
2.  when one-click install starts it will ask for your root password.
3.  once password is entered it will come up with a window stating that libuuid package is not available and strongly encourages you not to install.
[conflicts.txt](https://github.com/getferdi/ferdi/files/7688860/conflicts.txt)

### Expected Behavior

click on rpm, enter password, package installed

### Actual Behavior

comes up with a package conflict

### Debug information

{"host":{"platform":"linux","release":"5.15.6-1-default","screens":[{"id":1881264395124816,"bounds":{"x":0,"y":0,"width":1366,"height":768},"workArea":{"x":0,"y":0,"width":1366,"height":724},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1366,"height":768},"displayFrequency":60,"workAreaSize":{"width":1366,"height":724},"scaleFactor":1,"rotation":0,"internal":true,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{"id":"facebook","version":"1.1.2"},{"id":"hangoutschat","version":"1.5.1"},{"id":"messenger","version":"1.3.3"},{}],"devRecipes":[],"services":[{"id":"557b9763-d159-42c8-a43e-260fe16ed11b","recipe":"hangoutschat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"62b80457-d156-4973-a178-308399219f37","recipe":"messenger","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"ae224d29-8011-4813-b2e3-b83b0ad86895","recipe":"facebook","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/app/Ferdi/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/app/Ferdi/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/app/Ferdi/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/app/Ferdi/resources/app.asar/routes.js:1:2781)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/app/Ferdi/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/app/Ferdi/resources/app.asar/I18n.js:1:842)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/app/Ferdi/resources/app.asar/components/layout/Sidebar.js:1:2094)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (/app/Ferdi/resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/app/Ferdi/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/app/Ferdi/resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/app/Ferdi/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/app/Ferdi/resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/app/Ferdi/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/app/Ferdi/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/app/Ferdi/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/app/Ferdi/resources/app.asar/routes.js:1:2781)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/app/Ferdi/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/app/Ferdi/resources/app.asar/I18n.js:1:842)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (/app/Ferdi/resources/app.asar/features/nightlyBuilds/Component.js:1:2135)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Jss (/app/Ferdi/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (/app/Ferdi/resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/app/Ferdi/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/app/Ferdi/resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/app/Ferdi/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/app/Ferdi/resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/app/Ferdi/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/app/Ferdi/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/app/Ferdi/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/app/Ferdi/resources/app.asar/routes.js:1:2781)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/app/Ferdi/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/app/Ferdi/resources/app.asar/I18n.js:1:842)\n    at Injector (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/app/Ferdi/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":1366,"height":695,"x":0,"y":29,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1366,"height":768}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://tasks.google.com/embed/?origin=https%3A%2F%2Fcalendar.google.com&fullWidth=1","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"inactivityLock":0,"automaticUpdates":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US","customTodoServer":""},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by dap39** [comment]
Same here using openSUSE Tumbleweed and openSUSE Leap 15.3.
Thing is that if you ignore the warning Ferdi is working as expected.
