### ISSUE TITLE
Issue with Windows code signing certificate

### ISSUE THREAD

**Issue by crscaballero** [getferdi/ferdi#2380]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.6 

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11 Pro version 21H2

### What arch are you using?

x64

### Steps to reproduce

1. Go to Settings
2. Click on "Check for updates"
3. Wait and then you will have the error message "An error occurred (check the console for more details)" 

### Expected Behavior

Be able to update it

### Actual Behavior

Not update after found and download the new update

### Screenshots

![image](https://user-images.githubusercontent.com/48134692/147890747-587a23e7-6d92-46f2-854c-f3621abb5e2e.png)

### Additional Information

I saw previously this issue on the version 5.6.5 and what I did was download the latest version from Ferdi website and install it, but now I'm having the same situation with version 5.6.6 and I'm still not able to update it

**Comment by mycanaletto** [comment]
I had this problem and simply restarted the setup...

**Comment by kytwb** [comment]
What is the error?

You can see it in the console via **View > Toggle Developer Tools**.

**Comment by crscaballero** [comment]
> What is the error?
> 
> You can see it in the console via **View > Toggle Developer Tools**.

```is not signed by the application owner: publisherNames: Amine Mouafik, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=Sectigo RSA Code Signing CA, O=Sectigo Limited, L=Salford, S=Greater Manchester, C=GB",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1653436799000)/",
    "NotBefore": "/Date(1621814400000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "0096C411FF58A1164E298F64605962A440",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "76D51A804EFD879E802E04A9F07175D6F298C165",
    "Version": 3,
    "Issuer": "CN=Sectigo RSA Code Signing CA, O=Sectigo Limited, L=Salford, S=Greater Manchester, C=GB",
    "Subject": "CN=Amine Moufik, O=Amine Moufik, L=Casablanca, C=MA"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1925424000000)/",
    "NotBefore": "/Date(1609459200000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "0D424AE0BE3A88FF604021CE1400F0DD",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp 2021, O=\"DigiCert, Inc.\", C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3",
    "Version": 3,
    "Handle": 2884478632064,
    "Issuer": "CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=DigiCert Timestamp 2021, O=\"DigiCert, Inc.\", C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature verified."
}```

By the way, I wasn't able to open the console log via `View > Toggle Developer Tools.`, I had to use the shortcut, so that seems another bug

**Comment by kytwb** [comment]
@all-contributors please add @crscaballero for userTesting

**Comment by kytwb** [comment]
@crscaballero please share the error in full; it starts with `Updater error:`.

**Comment by crscaballero** [comment]
> @crscaballero please share the error in full; it starts with `Updater error:`.

sorry for that

```

Updater error: Error: New version 5.6.7 is not signed by the application owner: publisherNames: Amine Mouafik, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=Sectigo RSA Code Signing CA, O=Sectigo Limited, L=Salford, S=Greater Manchester, C=GB",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1653436799000)/",
    "NotBefore": "/Date(1621814400000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "0096C411FF58A1164E298F64605962A440",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "76D51A804EFD879E802E04A9F07175D6F298C165",
    "Version": 3,
    "Issuer": "CN=Sectigo RSA Code Signing CA, O=Sectigo Limited, L=Salford, S=Greater Manchester, C=GB",
    "Subject": "CN=Amine Moufik, O=Amine Moufik, L=Casablanca, C=MA"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1925424000000)/",
    "NotBefore": "/Date(1609459200000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "0D424AE0BE3A88FF604021CE1400F0DD",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp 2021, O=\"DigiCert, Inc.\", C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3",
    "Version": 3,
    "Handle": 2884478632064,
    "Issuer": "CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=DigiCert Timestamp 2021, O=\"DigiCert, Inc.\", C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature verified."
}
    at Object.newError (C:\Users\cris\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\builder-util-runtime\out\index.js:47:19)
    at Object.task (C:\Users\cris\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:39:50)
    at async NsisUpdater.executeDownload (C:\Users\cris\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:516:13)

```

**Comment by fearlesschicken** [comment]
If you try to install it after downloading manually, you'll see the error for the cert too.

![image](https://user-images.githubusercontent.com/1131992/148274749-5b70dbaa-9c28-41d0-81a5-adad7fe47e9e.png)

**Comment by crscaballero** [comment]
also, I've just noticed that in Mac is not working either, but the error is different

```
Updater error: HttpError: 404 
"method: GET url: https://github.com/getferdi/ferdi/releases/download/v5.6.9-nightly.0/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 05 Jan 2022 19:27:40 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "ECA6:2A21:371B07D:5E8A605:61D5F12C"
}
    at createHttpError (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:394:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:6816)
    at SimpleURLLoaderWrapper.emit (node:events:394:28)
```

**Comment by kytwb** [comment]
<img width="397" alt="Screen Shot 2022-01-07 at 8 22 50 PM" src="https://user-images.githubusercontent.com/412895/148596200-62bc3b11-b2e0-4ba5-a95d-def980abc36f.png">

![Screen Shot 2022-01-07 at 8 27 28 PM](https://user-images.githubusercontent.com/412895/148596603-7a9ddf29-b1f9-48a0-9874-bd312320c693.png)
