### ISSUE TITLE
No tray icon on RHEL + GNOME

### ISSUE THREAD

**Issue by petr-nehez** [getferdi/ferdi#437]
**Describe the bug**
There is no tray icon on GNOME running on RHEL.

**To Reproduce**
Install Ferdi via flatpak and add Skype service.
(AppImage could not bet started on my system, I get this error `bash: ./Ferdi-5.4.3.AppImage: Text file busy`)

**Expected behavior**
An icon in the tray at the top where e.g. Slack's icon is located.

**Screenshots**
![image](https://user-images.githubusercontent.com/1265990/75869972-a0485400-5e0a-11ea-8319-0d9e50abc637.png)

**Desktop:**

- OS: RHEL 8.1 + GNOME 3.32.2
- Ferdi Version: 5.4.3
- Server Used: https://api.getferdi.com

Debug information: 
```
{"host":{"platform":"linux","release":"4.18.0-147.5.1.el8_1.x86_64","screens":[{"accelerometerSupport":"unknown","bounds":{"height":1080,"width":1920,"x":0,"y":267},"colorDepth":24,"colorSpace":"{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}","depthPerComponent":8,"id":13761487533244520,"internal":false,"monochrome":false,"rotation":0,"scaleFactor":1,"size":{"height":1080,"width":1920},"touchSupport":"unknown","workArea":{"height":1080,"width":1920,"x":0,"y":267},"workAreaSize":{"height":1080,"width":1920}},{"accelerometerSupport":"unknown","bounds":{"height":1080,"width":1920,"x":1920,"y":0},"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6583, 0.3342],  [0.3420, 0.6034],  [0.1603, 0.0680]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"id":6125579703171434,"internal":false,"monochrome":false,"rotation":0,"scaleFactor":1,"size":{"height":1080,"width":1920},"touchSupport":"unknown","workArea":{"height":1080,"width":1920,"x":1920,"y":0},"workAreaSize":{"height":1080,"width":1920}}]},"ferdi":{"version":"5.4.3","electron":"7.1.6","installedRecipes":[{"id":"skype","version":"1.2.0"},{}],"devRecipes":[],"services":[{"id":"33b92e4f-3c9f-4c2d-b2fe-8e725af7caa6","recipe":"skype","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":1492,"height":779,"x":2103,"y":221,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":1920,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"enableSystemTray":true,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"enableSpellchecking":false,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","todoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernationStrategy":300,"inactivityLock":0,"noUpdates":false,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by reginastracii** [comment]
same on arch + gnome 3.34.4

**Comment by keunes** [comment]
Did anyone test with the deb package? I had that installed before, and don't remember whether or not this issue was there, too.

**Comment by hundertzwoelf** [comment]
No icon for me as well. 

Installed via the .deb package.
Running Ubuntu 19.10 using i3-gnome.

**Comment by danieltomasz** [comment]
Same for Ubuntu 20.04 and Gnome 3.36

I read that there was some problem with electrons apps https://github.com/electron/electron/issues/21445

**Comment by danieltomasz** [comment]
There is a solution https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150

**Comment by alien2003** [comment]
Icon disappears after unlock, Ubuntu 18.04

**Comment by don-andruha** [comment]
You closed #697, that's why I duplicate my feedback here.

I checked your nightly [build 5.5.1-nightly.14](https://github.com/getferdi/nightlies/releases/tag/v5.5.1-nightly.14) on **Linux Mint 19**, but did not see any changes. 
Tray icon still missing.

**Comment by hundertzwoelf** [comment]
Something I noticed is that, for me, it _works_ on Ferdi 5.4.4-beta.1, but not on 5.4.4-beta.2. In the second beta it got upgraded to Electron 8.0.0 and the release notes indicate 'enhanced system tray icon behaviour'.

**Comment by kytwb** [comment]
@don-andruha Thank you for your feedback 🙏
@hundertzwoelf Thank you for taking a look into it 🙏 There was a regression introduced via the enhancement you mentioned (😅 guilty), which got fixed via https://github.com/getferdi/ferdi/pull/741, for the context menu on Linux at least. I don't have a Linux VM to try to reproduce the missing icon part at the moment, but it could well be related to the upgrade to Electron 8.

**Comment by pamela-p6** [comment]
same here, noticed:
TypeError: Cannot read property 'setContextMenu' of null
at TrayIcon._updateTrayMenu (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1251)
at IpcMainImpl. (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1683)
at IpcMainImpl.emit (events.js:215:7)
at WebContents. (electron/js2c/browser_init.js:3851:15)
at WebContents.emit (events.js:210:5)
TypeError: Cannot read property 'setContextMenu' of null
at TrayIcon._updateTrayMenu (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1251)
at IpcMainImpl. (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1683)
at IpcMainImpl.emit (events.js:215:7)
at WebContents. (electron/js2c/browser_init.js:3851:15)
at WebContents.emit (events.js:210:5)

@ol7(RHEL) + mate + build 5.5.1-nightly.14

**Comment by kris7t** [comment]
Interestingly, for me, after building the ea5a5932 from the `develop` branch with Electron 8.2.5, the tray icon appears on Waybar (I use sway as a Wayland compositor), if I run Ferdi in release mode (`ELECTRON_IS_DEV=0`). In dev mode, however, I do errors with calling `setContextMenu` on `null`. I also get similar errors when I toggle "Show Ferdi in system tray" to off.

When I restart Waybar (`org.kde.StatusNotifierWatcher` disappears from the session D-Bus, the reappears as the new Waybar instance is initialized), the tray icon disappears. However, it comes back when I toggle "Show Ferdi in system tray" to off and then back on. I guess we would have similar behavior in GNOME Shell whenever the screen is locked.

**Comment by arnishow** [comment]
> Interestingly, for me, after building the [ea5a593](https://github.com/getferdi/ferdi/commit/ea5a5932605894ae46cfdbc0e784eaebae380cd9) from the `develop` branch with Electron 8.2.5, the tray icon appears on Waybar (I use sway as a Wayland compositor), if I run Ferdi in release mode (`ELECTRON_IS_DEV=0`). In dev mode, however, I do errors with calling `setContextMenu` on `null`. I also get similar errors when I toggle "Show Ferdi in system tray" to off.
> 
> When I restart Waybar (`org.kde.StatusNotifierWatcher` disappears from the session D-Bus, then reappears as the new Waybar instance is initialized), the tray icon disappears. However, it comes back when I toggle "Show Ferdi in system tray" to off and then back on. I guess we would have similar behavior in GNOME Shell whenever the screen is locked.

I confirm the exact same behavior with Gnome Shell.

**Comment by kris7t** [comment]
@arnishow Can you try this patch? https://github.com/getferdi/ferdi/pull/748 I only tried with Waybar, but it should also fix the issue for GNOME Shell.

**Comment by kytwb** [comment]
@kris7t's patch has been made available in [v5.5.1-nightly.15](https://github.com/getferdi/nightlies/releases/tag/v5.5.1-nightly.15).

**Comment by arnishow** [comment]
@kris7t Works well with GShell using deb package v5.5.1-nightly.15, thanks a lot.

**Comment by alien2003** [comment]
@kris7t it works!

**Comment by pirasalbe** [comment]
@kris7t still not working with Linux Mint 19.3 using deb v5.5.1-nightly.15.

**Comment by kris7t** [comment]
@pirasalbe What desktop environment are you using? If it's Cinnamon, I think the culprit would be the lack of AppIndicator (StatusNotifierWatcher) support: https://github.com/linuxmint/cinnamon/issues/9176 It seems a patch was merged, but only very recently, so no wonder it's not part of 19.3.

You can check for AppIndicator support with the following command:
```
dbus-send --session --dest=org.kde.StatusNotifierWatcher --print-reply /StatusNotifierWatcher org.freedesktop.DBus.Properties.Get string:org.kde.StatusNotifierWatcher string:IsStatusNotifierHostRegistered
```

**Comment by MarvinMep** [comment]
I was facing this problem on my Debian 10 (gnome-Xorg). There was no way to make it show the Ferdi's icon (all other icon were there). 

Before I came here, I though it was a problem with the gnome-shell extension (TopIcon Redux), since system tray is not native in gnome (as you must know, Gnome devs think system tray a outdated concept). So I started to mess with the extensions and I end up with "[KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/)" debian counterpart [appindicator](https://packages.debian.org/buster/gnome-shell-extension-appindicator), when I gave up. Ferdi icon still didn't work.

Since I was there, I kept messing with extensions and adjusts, customizing other stuff. I realized that when I turned off "app menu"  in "Gnome adjusts"/"Superior bar" (I don't know how is the names exactly, I use pt-Br localization) Ferdi icon showed up and never went away.

Now, with Appindicator (gnome-shell extension) and apps menus disabled in shell bar, Ferdi icon works like a charm.

- Debian 10.4
- Xorg 7.7
- Gnome-shell 3.30.2 (?)
- Ferdi 5.5.0 (x64) (installed from .deb)
- gnome-shell-extension-appindicator 22-1
- [Remove Dropdown Arrows](https://extensions.gnome.org/extension/800/remove-dropdown-arrows/) (it may be influencing, but I didn't try to remove it)

**Comment by andrecavallari** [comment]
I've tested now the 5.6.0-beta.2, and the system tray icon now shows up, but after a while the system tray just disappear, and to have it back I need to disable this feature and enable again to show up, but again after a while it's gone again...

**Comment by ilopmar** [comment]
I just tried with Linux Mint 20 Cinnamon (updated from Linux Mint 19.3) and the systray icon doesn't appear. I've tried versions 5.5.0, 5.5.1-nightly.14, 5.5.1-nightly.15 and 5.6.0-beta2.

**Comment by tchiotludo** [comment]
same here with 5.6.0-beta2 and a fresh Linux Mint 20 Cinnamon, no tray icon anymore

**Comment by tamas646** [comment]
Still no tray icon for me. Debian 10, GNOME 3.30.2
Tried 5.5.1-nightly.15, but nothing changed.

**Comment by GregoryHorvath** [comment]
+1 I'm also missing the tray icon (and not sure how to open preferences otherwise...) on Pop OS! 20.04.1 with GNOME.

**Comment by hakanalpp** [comment]
+1 I'm also missing the tray icon on Fedora 33 and Gnome xorg

**Comment by MarcioFCMartins** [comment]
Pop_OS 20.10 - The icon usually shows up correctly at start-up, but disappears after locking and unlocking screen. 
I think sometimes it disappears without locking but I am not totally sure.

**Comment by leoheck** [comment]
I still don't see any tray icon on Ubuntu 20.04. How do we fix this? Any workaround?

**Comment by bittner** [comment]
Current status on Ubuntu:

- Deb package v5.6.5 successfully shows tray icon :heavy_check_mark: 
- Snap package v5.6.5 successfully shows tray icon :heavy_check_mark: 
- Flatpak package v5.6.5 shows no tray icon :x: 

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

Errors shown in the console when launching (and terminating) Ferdi: 
```console
$ flatpak run com.getferdi.Ferdi 
[2 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: No such property 'supports'
[2 zypak-helper] Portal v4 is not available
Gtk-Message: 14:59:03.264: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:59:03.264: Failed to load module "canberra-gtk-module"
[2:1226/145903.277401:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
[34:1226/145903.425952:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[2:1226/145904.813501:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1226/145904.813551:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1226/145904.813580:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
error: fstat: Bad file descriptor
[10 zypak-sandbox] Dropping 0x55e40e6d72c0 (3) because of connection closed
[10 zypak-sandbox] Host is gone, preparing to exit...
[10 zypak-sandbox] Quitting Zygote...
```

Does that say we have a Flatpak issue only now?
