### ISSUE TITLE
Error loading js modules when starting app

### ISSUE THREAD

**Issue by RoiArthurB** [getferdi/ferdi#505]
**Describe the bug**
I have an error when launching Ferdi, looks like a lib which can't be load :/

**To Reproduce**

1. Start the app
2. See the error when starting

**Expected behavior**
Application launching

**Logs**
```
$ ferdi            
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:28030) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:28030) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:28030) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:28030) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
Starting local server on port 45569
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/usr/lib/ferdi/app.asar/node_modules/sqlite3/lib/binding/electron-v8.2-linux-x64/node_sqlite3.node'
Require stack:
- /usr/lib/ferdi/app.asar/node_modules/sqlite3/lib/sqlite3.js
- /usr/lib/ferdi/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js
- /usr/lib/ferdi/app.asar/node_modules/knex/lib/index.js
- /usr/lib/ferdi/app.asar/node_modules/knex/knex.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/lucid/src/Database/index.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/lucid/src/Database/Manager.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/lucid/providers/LucidProvider.js
- /usr/lib/ferdi/app.asar/node_modules/require-stack/src/index.js
- /usr/lib/ferdi/app.asar/node_modules/require-stack/index.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/fold/src/Ioc/index.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/fold/index.js
- /usr/lib/ferdi/app.asar/internal-server/start.js
- /usr/lib/ferdi/app.asar/electron/ipc-api/localServer.js
- /usr/lib/ferdi/app.asar/electron/ipc-api/index.js
- /usr/lib/ferdi/app.asar/index.js
- /usr/lib/electron/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7607:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/ferdi/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
info: serving app on http://127.0.0.1:45569
```

**Desktop:**

- OS: Manjaro 19.0.2
- Ferdi Version: `aur/ferdi 5.4.3-8`
- Server Used: None

Debug information: https://debug.getferdi.com/...

**Additional context**
Here's some more informations : 
```
$ npm -v
6.14.4

$ electron -v
v8.2.0

$ ls -la /usr/lib/ferdi 
total 160M
drwxr-xr-x   3 root root 4,0K 27 mars  00:46 .
drwxr-xr-x 245 root root 192K 28 mars  10:53 ..
-rw-r--r--   1 root root 160M 27 mars  00:39 app.asar
drwxr-xr-x   3 root root 4,0K 23 mars  11:31 app.asar.unpacked
```
Trying to install SQLite3 do not resolve my bug...
```
$ npm install sqlite3 --save

> sqlite3@4.1.1 install /home/roiarthurb/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/home/roiarthurb/node_modules/sqlite3/lib/binding/node-v79-linux-x64/node_sqlite3.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open '/home/roiarthurb/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/roiarthurb/package.json'
npm WARN roiarthurb No description
npm WARN roiarthurb No repository field.
npm WARN roiarthurb No README data
npm WARN roiarthurb No license field.

+ sqlite3@4.1.1
updated 1 package and audited 687 packages in 4.848s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by RoiArthurB** [comment]
Problem fixed with the GIT version. I think the problem is that Electron has been updated on Manjaro and it's not compatible anymore with the stable version of Ferdi 🤷

**Comment by kytwb** [comment]
@RoiArthurB Thanks for your feedback; we have updated Electron in our latest betas, this will land in the next stable release 🙏

**Comment by kytwb** [comment]
I experienced this in development when trying to use Ferdi without an account on my macOS.

**Comment by kytwb** [comment]
Fixed by removing `node_modules` and re-running `npx lerna bootsrap`.

**Comment by yourcontact** [comment]
I am posting my bug in this issue since it might related.







### Expected Behavior



Ferdi dev environment should launch via Electron.

### Current Behavior



Ferdi dev environment does not launch via Electron. 

### Screenshots (if appropriate):



### Possible Solution



### Steps to Reproduce (for bugs)



- ran `git reset --hard origin/develop`
- ran `git status`: `On branch develop nothing to commit, working tree clean`
- ran `npm i -D electron@latest` to check  if Electron was up-to-date by running

Below is what I got in my terminal:
<img width="1416" alt="Screenshot 2020-05-05 at 15 24 40" src="https://user-images.githubusercontent.com/46404814/81072090-ed69a480-8ee5-11ea-8604-8e35971f0770.png">

- found this issue (and comment https://github.com/getferdi/ferdi/issues/505#issuecomment-605433518)
- I am not sure how to remove `node_modules`.  
- ran `npx lerna bootstrap`
- Electron's window popped up and crashed immediately.

Below is what I got in my terminal:
<img width="707" alt="Screenshot 2020-05-05 at 15 49 46" src="https://user-images.githubusercontent.com/46404814/81073541-11c68080-8ee8-11ea-9ba3-939ae8344e75.png">

<img width="709" alt="Screenshot 2020-05-05 at 15 49 35" src="https://user-images.githubusercontent.com/46404814/81073550-14c17100-8ee8-11ea-91e3-a2e6de362fa3.png">


### Context



I am trying to launch Ferdi locally to work on #651 


### Your Environment

* Ferdi Version used: 
* Operating System and version: MacOS Mojave 10.14.6 (18G4032)
* Electron 8.2.5

**Comment by yourcontact** [comment]
I had a quick chat with @kytwb who clarified on [the fix](https://github.com/getferdi/ferdi/issues/505#issuecomment-605433518). 🙏🏻

That is:

```
git reset --hard origin/develop
rm -rf node_modules
npx lerna bootstrap
npx misty
```
