### ISSUE TITLE
error when trying setup a new acount.

### ISSUE THREAD

**Issue by M0UL** [getferdi/ferdi#690]
i am trying to setup a new fredi acount. i am getting 401 errors form the fredi api.
i am using version. 5.5 on windows 10

**Comment by mysterfr** [comment]
Hello,

Reporting the same exact issue, witnessed on Windows 10, Debian 10 and Ubuntu 20.04.

Cheers !

**Comment by kytwb** [comment]
I wasn't able to reproduce and managed to create a new account:

<img width="1270" alt="Screen Shot 2020-05-03 at 11 18 15 AM" src="https://user-images.githubusercontent.com/412895/80912910-e6993100-8d2f-11ea-90af-96c93c89763c.png">

I do see errors/401 related to Franz in the logs (https://api.franzinfra.com/v1/me):

```
0|Ferdi_AP | { FetchError: invalid json response body at https://api.franzinfra.com/v1/me reason: Unexpected end of JSON input
0|Ferdi_AP |     at /home/ubuntu/server/node_modules/node-fetch/lib/index.js:272:32
0|Ferdi_AP |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

We could better handle this on our side.
Can you both confirm your server is set as follow?

<img width="635" alt="Screen Shot 2020-05-03 at 11 25 44 AM" src="https://user-images.githubusercontent.com/412895/80913038-d59cef80-8d30-11ea-9af4-ddb1a640df2d.png">

<img width="465" alt="Screen Shot 2020-05-03 at 11 23 07 AM" src="https://user-images.githubusercontent.com/412895/80913044-dc2b6700-8d30-11ea-8c84-a1f00225df58.png">

**Comment by mysterfr** [comment]
[-1588501886584.log](https://github.com/getferdi/ferdi/files/4570232/-1588501886584.log)
[-1588501833277.log](https://github.com/getferdi/ferdi/files/4570233/-1588501833277.log)

I confirm the configured URL is https://api.getferdi.com. (default)

Please see details logs attached.
These are the last two events related to the 401 issue on an Kubuntu 20.04 system, Ferdi installed from DEB.

Thanks !
