### ISSUE TITLE
Arch with Electron 9

### ISSUE THREAD

**Issue by larsmagnusherland** [getferdi/ferdi#786]
When installing Ferdi through Yaourt it is installed alongside Electron 9.0.1 (as of june 3rd) and not 8.2
This makes some parts of the application not work as it should.

**Steps to reproduce:**
1. Log in
2. Add a service (example is Skype)
3. The "loading screen" is stuck and you cannot get past it and use the service loaded behind it.

**Expected behavior**
Working service

**Screenshots**
![image](https://user-images.githubusercontent.com/16826379/83340178-5f5ebf00-a2d5-11ea-9e9d-43d7e561c316.png)

**Environment:**

- Operating System: Arch Linux 5.6 kernel
- Ferdi Version: 5.5.0-4
- Server: Ferdi

- Debug information:
Following errors are printed to the terminal:
```
Error: Failed to serialize arguments
    at WebContents../lib/browser/api/web-contents.js.WebContents.send (electron/js2c/browser_init.js:3763:15)
    at IpcMainImpl.<anonymous> (/usr/lib/ferdi/app.asar/electron/ipc-api/settings.js:1:210)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:4093:15)
    at WebContents.emit (events.js:223:5)
Error: Failed to serialize arguments
    at WebContents../lib/browser/api/web-contents.js.WebContents.send (electron/js2c/browser_init.js:3763:15)
    at IpcMainImpl.<anonymous> (/usr/lib/ferdi/app.asar/electron/ipc-api/settings.js:1:210
```
Errors from developer tools:
```
deprecate.ts:33 (electron) crashReporter.start is deprecated in the renderer process. Call it from the main process instead.
log @ deprecate.ts:32
/usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js:104 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]' TypeError: Cannot read property 'pathname' of null
    at _requireAuthenticatedUser (/usr/lib/ferdi/app.asar/stores/UserStore.js:1)
    at reactionRunner (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:2097)
    at trackDerivedFunction (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:759)
    at Reaction.track (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1787)
    at Reaction.onInvalidate (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:2078)
    at Reaction.runReaction (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1753)
    at runReactionsHelper (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1890)
    at reactionScheduler (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1868)
    at /usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1897
    at bk (/usr/lib/ferdi/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:224)
    at reactionScheduler (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1897)
    at runReactions (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1873)
    at Reaction.schedule (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:1737)
    at autorun (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:2099)
    at Reaction.start (/usr/lib/ferdi/app.asar/stores/lib/Reaction.js:1)
    at /usr/lib/ferdi/app.asar/stores/lib/Store.js:1
    at Array.forEach (<anonymous>)
    at _temp.initialize (/usr/lib/ferdi/app.asar/stores/lib/Store.js:1)
    at /usr/lib/ferdi/app.asar/stores/index.js:1
    at Array.forEach (<anonymous>)
    at _default (/usr/lib/ferdi/app.asar/stores/index.js:1)
    at app.js:1
    at sentryWrapped (/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:74)
(anonymous) @ /usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js:104
/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:91 Uncaught Error: An object could not be cloned.
    at EventEmitter../lib/renderer/api/ipc-renderer.ts.ipcRenderer.send (ipc-renderer.ts:10)
    at /usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/renderer/backend.js:45
    at /usr/lib/ferdi/app.asar/node_modules/@sentry/hub/dist/scope.js:50
    at Array.forEach (<anonymous>)
    at /usr/lib/ferdi/app.asar/node_modules/@sentry/hub/dist/scope.js:49
    at sentryWrapped (/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:74)
/usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js:104 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ /usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js:104
/usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js:104 Could not connect to Sentry main process. Did you call init?
(anonymous) @ /usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js:104
index.html#/:1 A cookie associated with a cross-site resource at http://api.getferdi.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:91 Uncaught TypeError: this.webview.getWebContents is not a function
    at _temp.initializeWebViewEvents (/usr/lib/ferdi/app.asar/models/Service.js:1)
    at _temp._setWebviewReference (/usr/lib/ferdi/app.asar/stores/ServicesStore.js:1)
    at executeAction (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:905)
    at _temp.res (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:897)
    at /usr/lib/ferdi/app.asar/actions/lib/actions.js:1
    at Array.forEach (<anonymous>)
    at Function.i.notify (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at i (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at Object.onDidAttach (/usr/lib/ferdi/app.asar/components/services/content/ServiceWebview.js:1)
    at HTMLElement.<anonymous> (/usr/lib/ferdi/app.asar/node_modules/react-electron-web-view/lib/ElectronWebView.js:21413)
    at HTMLElement.sentryWrapped (/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:74)
    at WebViewImpl.dispatchEvent (web-view-impl.ts:120)
    at dispatchEvent (guest-view-internal.ts:59)
    at EventEmitter.<anonymous> (guest-view-internal.ts:77)
    at EventEmitter.emit (events.js:223)
    at EventEmitter.emit (domain.js:475)
    at Object.onMessage (init.ts:50)
/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:91 Uncaught TypeError: this.webview.getWebContents is not a function
    at _temp.initializeWebViewEvents (/usr/lib/ferdi/app.asar/models/Service.js:1)
    at _temp._setWebviewReference (/usr/lib/ferdi/app.asar/stores/ServicesStore.js:1)
    at executeAction (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:905)
    at _temp.res (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:897)
    at /usr/lib/ferdi/app.asar/actions/lib/actions.js:1
    at Array.forEach (<anonymous>)
    at Function.i.notify (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at i (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at Object.onDidAttach (/usr/lib/ferdi/app.asar/components/services/content/ServiceWebview.js:1)
    at HTMLElement.<anonymous> (/usr/lib/ferdi/app.asar/node_modules/react-electron-web-view/lib/ElectronWebView.js:21413)
    at HTMLElement.sentryWrapped (/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:74)
    at WebViewImpl.dispatchEvent (web-view-impl.ts:120)
    at dispatchEvent (guest-view-internal.ts:59)
    at EventEmitter.<anonymous> (guest-view-internal.ts:77)
    at EventEmitter.emit (events.js:223)
    at EventEmitter.emit (domain.js:475)
    at Object.onMessage (init.ts:50)
/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:91 Uncaught TypeError: this.webview.getWebContents is not a function
    at _temp.initializeWebViewEvents (/usr/lib/ferdi/app.asar/models/Service.js:1)
    at _temp._setWebviewReference (/usr/lib/ferdi/app.asar/stores/ServicesStore.js:1)
    at executeAction (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:905)
    at _temp.res (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:897)
    at /usr/lib/ferdi/app.asar/actions/lib/actions.js:1
    at Array.forEach (<anonymous>)
    at Function.i.notify (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at i (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at Object.onDidAttach (/usr/lib/ferdi/app.asar/components/services/content/ServiceWebview.js:1)
    at HTMLElement.<anonymous> (/usr/lib/ferdi/app.asar/node_modules/react-electron-web-view/lib/ElectronWebView.js:21413)
    at HTMLElement.sentryWrapped (/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:74)
    at WebViewImpl.dispatchEvent (web-view-impl.ts:120)
    at dispatchEvent (guest-view-internal.ts:59)
    at EventEmitter.<anonymous> (guest-view-internal.ts:77)
    at EventEmitter.emit (events.js:223)
    at EventEmitter.emit (domain.js:475)
    at Object.onMessage (init.ts:50)
/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:91 Uncaught TypeError: this.webview.getWebContents is not a function
    at _temp.initializeWebViewEvents (/usr/lib/ferdi/app.asar/models/Service.js:1)
    at _temp._setWebviewReference (/usr/lib/ferdi/app.asar/stores/ServicesStore.js:1)
    at executeAction (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:905)
    at _temp.res (/usr/lib/ferdi/app.asar/node_modules/mobx/lib/mobx.js:897)
    at /usr/lib/ferdi/app.asar/actions/lib/actions.js:1
    at Array.forEach (<anonymous>)
    at Function.i.notify (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at i (/usr/lib/ferdi/app.asar/actions/lib/actions.js:1)
    at Object.onDidAttach (/usr/lib/ferdi/app.asar/components/services/content/ServiceWebview.js:1)
    at HTMLElement.<anonymous> (/usr/lib/ferdi/app.asar/node_modules/react-electron-web-view/lib/ElectronWebView.js:21413)
    at HTMLElement.sentryWrapped (/usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js:74)
    at WebViewImpl.dispatchEvent (web-view-impl.ts:120)
    at dispatchEvent (guest-view-internal.ts:59)
    at EventEmitter.<anonymous> (guest-view-internal.ts:77)
    at EventEmitter.emit (events.js:223)
    at EventEmitter.emit (domain.js:475)
    at Object.onMessage (init.ts:50)
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/types/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/types/dist/loglevel.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/types/dist/severity.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/types/dist/span.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/types/dist/status.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/minimal/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/hub/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/hub/dist/scope.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/async.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/error.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/polyfill.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/is.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/logger.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/misc.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/memo.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/object.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/string.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/path.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/promisebuffer.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/syncpromise.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/supports.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/dsn.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/hub/dist/hub.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/api.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/baseclient.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/integration.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/basebackend.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/sdk.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/transports/noop.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/integrations/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/integrations/functiontostring.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/core/dist/integrations/inboundfilters.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/common.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/dispatch.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/sdk.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/renderer/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/client.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/backend.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/eventbuilder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/parsers.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/tracekit.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/transports/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/transports/base.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/transports/fetch.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/transports/xhr.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/version.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/sdk.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/helpers.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/integrations/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/integrations/globalhandlers.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/integrations/trycatch.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/integrations/breadcrumbs.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/integrations/linkederrors.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/browser/dist/integrations/useragent.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/renderer/client.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@sentry/electron/dist/renderer/backend.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/mobx-react-router/dist/mobx-react-router.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-messageformat/lib/main.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-messageformat/lib/core.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-messageformat/lib/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-messageformat/lib/es5.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-messageformat/lib/compiler.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-messageformat-parser/lib/parser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-messageformat/lib/en.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-relativeformat/lib/main.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-relativeformat/lib/core.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-relativeformat/lib/diff.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-relativeformat/lib/es5.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-relativeformat/lib/en.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-relativeformat/lib/locales.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/intl-format-cache/dist/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/input/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@mdi/react/Icon.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/error/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/error/styles.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/label/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/label/styles.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/wrapper/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/input/scorePassword.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/input/styles.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/toggle/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/button/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/forms/lib/select/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/ui/lib/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/ui/lib/icon/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/ui/lib/infobox/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/ui/lib/headline/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/ui/lib/loader/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/ui/lib/badge/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/ui/lib/badge/ProBadge.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/theme/lib/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/theme/lib/themes/dark/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/theme/lib/themes/default/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/@meetfranz/theme/lib/themes/legacy/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/lib/ferdi/app.asar/node_modules/react-confetti/dist/react-confetti.min.js.map: 
```

**Comment by n0emis** [comment]
Maybe it is because of this?
```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

(this error appears when starting ferdi with Electron 8.2.5)

**Comment by kris7t** [comment]
In the very short term, you can downgrade to Electron 8 (using something like `pacman -U /var/cache/pacman/pkg/electron-8.2.5-2-x86_64.pkg.tar.zst`), but note that leads to a partially updated system and in entirely unsupported by Arch maintainers. Alternatively, you can try the [ferdi-bin](https://aur.archlinux.org/packages/ferdi-bin/) AUR package, which is extracted from the Fedora rpms for Ferdi and comes with its own Electron distribution (which makes it somewhat large, though).

In the short term, an `electron8` package might be included in Arch (there is already an `electron7` package, for instance). Then the `ferdi` AUR package could be build with `electron8` instead of `electron`. There is already an [electron8-bin](https://aur.archlinux.org/packages/electron8-bin/) package, but it currently refers to an out-of-date Electron 8 release. Note that merely installing this package won't fix Ferdi. For that, you need to rebuild Ferdi to reference the installed Electron 8 binaries instead of the Electron 9 binaries (see the [Electron package guidelines](https://wiki.archlinux.org/index.php/Electron_package_guidelines) in the Arch Wiki).

In the long term, we should fix Ferdi to run under Electron 9. This will allow cool things like [Chrome extension support](https://github.com/getferdi/ferdi/issues/113#issuecomment-603238109). However, the work required is [far from trivial](https://github.com/orgs/getferdi/projects/3).

**Comment by dpeukert** [comment]
AUR package maintainer here, yeah, I was waiting for a bit to see if an electron8 package gets pushed to the repo, but I'll switch to `electron8-bin` for now.

**Comment by schinfo** [comment]
This will fix the problem

[ferdi.zip](https://github.com/getferdi/ferdi/files/4707758/ferdi.zip)

**Comment by jmg87** [comment]
schinfo ' s patch did it for me (though it was a big compile  in my system). Thanks!

**Comment by larsmagnusherland** [comment]
@schinfo this solved it for me. Awesome! Thank you!

For those who need it but don't know how to apply the patch, these are the steps:
Extract the file provided by @schinfo , navigate to the folder where it extracted to and run:
makepkg PKGBUILD
after it being done run:
sudo pacman -U /FOLDERS_TO_.tar.xz_file/

**Comment by Naragorn** [comment]
I have the same issue however the above patch did not fix things for me.
All my services have an infinite spinning loader and thus ferdi is unusable.

**Comment by dpeukert** [comment]
@schmunk42 I've adopted electron8-bin and fixed it as it was missing some files (and updated it as well). Can you try if it works now?

**Comment by schmunk42** [comment]
@dpeukert Yes, thank you! Ferdi is working again.

**Comment by kytwb** [comment]
I believe this was fixed via https://github.com/getferdi/ferdi/pull/809.
