### ISSUE TITLE
Sqlite3 bug on Manjaro ARM

### ISSUE THREAD

**Issue by louisabraham** [getferdi/ferdi#926]
I installed ferdi-git from https://privacyshark.zero-credibility.net/#packages
When launching, I get the following:

```
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
failed to load swrast driver
Starting local server on port 45569
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/usr/lib/ferdi/app.asar/node_modules/sqlite3/lib/binding/electron-v9.2-linux-arm64/node_sqlite3.node'                                                                                                         
Require stack:
- /usr/lib/ferdi/app.asar/node_modules/sqlite3/lib/sqlite3.js
- /usr/lib/ferdi/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js
- /usr/lib/ferdi/app.asar/node_modules/knex/lib/index.js
- /usr/lib/ferdi/app.asar/node_modules/knex/knex.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/lucid/src/Database/index.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/lucid/src/Database/Manager.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/lucid/providers/LucidProvider.js
- /usr/lib/ferdi/app.asar/node_modules/require-stack/src/index.js
- /usr/lib/ferdi/app.asar/node_modules/require-stack/index.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/fold/src/Ioc/index.js
- /usr/lib/ferdi/app.asar/node_modules/@adonisjs/fold/index.js
- /usr/lib/ferdi/app.asar/internal-server/start.js
- /usr/lib/ferdi/app.asar/electron/ipc-api/localServer.js
- /usr/lib/ferdi/app.asar/electron/ipc-api/index.js
- /usr/lib/ferdi/app.asar/index.js
- /usr/lib/electron/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/ferdi/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Client_SQLite3._driver (/usr/lib/ferdi/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:57:12)
    at Client_SQLite3.initializeDriver (/usr/lib/ferdi/app.asar/node_modules/knex/lib/client.js:250:26)
info: serving app on http://127.0.0.1:45569
warning:
  WARNING: Adonis has detected an unhandled promise rejection, which may
  cause undesired behavior in production.
  To stop this warning, use catch() on promises or wrap await
  calls inside try/catch.

TypeError: Cannot read property 'Database' of undefined
    at /usr/lib/ferdi/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:84:33
    at Promise._execute (/usr/lib/ferdi/app.asar/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/lib/ferdi/app.asar/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/lib/ferdi/app.asar/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_SQLite3.acquireRawConnection (/usr/lib/ferdi/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:83:12)
    at create (/usr/lib/ferdi/app.asar/node_modules/knex/lib/client.js:280:23)
    at /usr/lib/ferdi/app.asar/node_modules/tarn/lib/Pool.js:315:34
    at Object.tryPromise (/usr/lib/ferdi/app.asar/node_modules/tarn/lib/utils.js:53:24)
    at /usr/lib/ferdi/app.asar/node_modules/tarn/lib/Pool.js:315:17
    at new Promise (<anonymous>)
    at callbackOrPromise (/usr/lib/ferdi/app.asar/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/usr/lib/ferdi/app.asar/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/usr/lib/ferdi/app.asar/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/usr/lib/ferdi/app.asar/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/usr/lib/ferdi/app.asar/node_modules/tarn/lib/Pool.js:85:14)
    at /usr/lib/ferdi/app.asar/node_modules/knex/lib/client.js:335:26
```

**Comment by mhatvan** [comment]
Hey @louisabraham, there have been a lot of code improvements since you reported this issue, so it might have been fixed in the meantime.

You can try the latest nightly from here: https://github.com/getferdi/nightlies/releases

**Comment by mhatvan** [comment]
Closing due to inactivity.
